# Generated by Django 5.1.4 on 2026-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apns_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='app_version',
            field=models.CharField(default='', max_length=50),
        ),
    ]
