# Generated by Django 5.1.4 on 2026-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_initiat_117c3d_idx',
            old_name='calls_initiat_created_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_status_de57eb_idx',
            old_name='calls_status_idx',
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
