# Generated by Django 5.1.4 on 2026-02-26 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_encryption_fields_to_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_3ebb41_idx',
            old_name='messages_convers_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_sender__bf8b1c_idx',
            old_name='messages_sender__created_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='chat.ConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
