# Generated by Django 5.1.4 on 2026-02-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversationparticipant_cleared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
