# Generated by Django 5.1.4 on 2026-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_participant_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
