# Generated by Django 5.1.4 on 2026-02-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_participant_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
