# Generated by Django 5.1.4 on 2026-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparticipant',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
