# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_add_moderator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
