# Generated by Django 5.1.4 on 2026-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_add_participant_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparticipant',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
