# Generated by Django 5.1.4 on 2026-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeybundle',
            name='crypto_version',
            field=models.IntegerField(choices=[(1, 'X448/Ed448 (legacy)'), (2, 'X25519/Ed25519 (production)')], default=2, help_text='1=X448/Ed448 (legacy), 2=X25519/Ed25519 (production)'),
        ),
        migrations.AddField(
            model_name='userkeybundle',
            name='key_version',
            field=models.IntegerField(default=1, help_text='Incrementato ad ogni rotazione completa del bundle'),
        ),
    ]
